# Run `docker-compose build` to build an image for api and workers containers.
# Run `docker-compose up` to run all containers.

version: "3.4"

services:
  api:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: pdfservice
    command: ["api", "--host", "api", "--port", "8000"]
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - postgresql
      - rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq-user
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq-passwd
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-user-passwd
      POSTGRES_USER_NAME_FILE: /run/secrets/postgres-user-name
      POSTGRES_DB_FILE: /run/secrets/postgres-db
      POSTGRES_HOST: postgresql
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    secrets:
      - rabbitmq-user
      - rabbitmq-passwd
      - postgres-user-passwd
      - postgres-user-name
      - postgres-db

  rabbitmq:
    image: rabbitmq:3.8.18
    expose:
      - 5672
    ports:
      - 5672:5672
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq-user
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq-passwd
    secrets:
      - rabbitmq-user
      - rabbitmq-passwd

  postgresql:
    image: postgres:latest
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-admin-passwd
      POSTGRES_DB_FILE: /run/secrets/postgres-db
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
      - ./data/postgresql/init:/docker-entrypoint-initdb.d
    secrets:
      - postgres-admin-passwd
      - postgres-db

  workers:
    image: pdfservice
    command: ["processor"]
    restart: on-failure
    depends_on:
      - rabbitmq
      - postgresql
    environment:
      RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq-user
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq-passwd
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-user-passwd
      POSTGRES_USER_NAME_FILE: /run/secrets/postgres-user-name
      POSTGRES_DB_FILE: /run/secrets/postgres-db
      POSTGRES_HOST: postgresql
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    secrets:
      - rabbitmq-user
      - rabbitmq-passwd
      - postgres-user-passwd
      - postgres-user-name
      - postgres-db

secrets:
  postgres-admin-passwd:
    file: ./data/secrets/postgres-passwd.txt
  postgres-user-passwd:
    file: ./data/secrets/postgres-user-passwd.txt
  postgres-user-name:
    file: ./data/secrets/postgres-user-name.txt
  postgres-db:
    file: ./data/secrets/postgres-db.txt
  rabbitmq-user:
    file: ./data/secrets/rabbitmq-user.txt
  rabbitmq-passwd:
    file: ./data/secrets/rabbitmq-passwd.txt